bp_from_AD2019a <- read.table("bp_from_AD2019/bp_from_AD2019.all_score", header=T, sep=" ")
head(bp_from_AD2019a)
bp_from_AD2019a <- subset(bp_from_AD2019a, select=-c(1))
bp_from_AD2019b <- read.table("bp_from_AD2019/bp_from_AD2019.best", header=T, sep=" ")
head(bp_from_AD2019b)
bp_from_AD2019b <- subset(bp_from_AD2019b, select=c(2,4))
bp_from_AD2019c<- merge(bp_from_AD2019a,bp_from_AD2019b, by ="IID")
colnames(bp_from_AD2019c)<- c("IID","bp_from_AD2019_e8","bp_from_AD2019_e5","bp_from_AD2019_e3", "bp_from_AD2019_e1", "bp_from_AD2019_1.0", "bp_from_AD2019_best")
head(bp_from_AD2019c)
merge<- merge(merge, bp_from_AD2019c, by ="IID")
head(merge)


bp_from_ADHD_DBDa <- read.table("bp_from_ADHD_DBD/bp_from_ADHD_DBD.all_score", header=T, sep=" ")
head(bp_from_ADHD_DBDa)
bp_from_ADHD_DBDa <- subset(bp_from_ADHD_DBDa, select=-c(1))
bp_from_ADHD_DBDb <- read.table("bp_from_ADHD_DBD/bp_from_ADHD_DBD.best", header=T, sep=" ")
head(bp_from_ADHD_DBDb)
bp_from_ADHD_DBDb <- subset(bp_from_ADHD_DBDb, select=c(2,4))
bp_from_ADHD_DBDc<- merge(bp_from_ADHD_DBDa,bp_from_ADHD_DBDb, by ="IID")
colnames(bp_from_ADHD_DBDc)<- c("IID","bp_from_ADHD_DBD_e8","bp_from_ADHD_DBD_e5","bp_from_ADHD_DBD_e3", "bp_from_ADHD_DBD_e1", "bp_from_ADHD_DBD_1.0", "bp_from_ADHD_DBD_best")
head(bp_from_ADHD_DBDc)
merge<- merge(merge, bp_from_ADHD_DBDc, by ="IID")
head(merge)


bp_from_anorexiaa <- read.table("bp_from_anorexia/bp_from_anorexia.all_score", header=T, sep=" ")
head(bp_from_anorexiaa)
bp_from_anorexiaa <- subset(bp_from_anorexiaa, select=-c(1))
bp_from_anorexiab <- read.table("bp_from_anorexia/bp_from_anorexia.best", header=T, sep=" ")
head(bp_from_anorexiab)
bp_from_anorexiab <- subset(bp_from_anorexiab, select=c(2,4))
bp_from_anorexiac<- merge(bp_from_anorexiaa,bp_from_anorexiab, by ="IID")
colnames(bp_from_anorexiac)<- c("IID","bp_from_anorexia_e8","bp_from_anorexia_e5","bp_from_anorexia_e3", "bp_from_anorexia_e1", "bp_from_anorexia_1.0", "bp_from_anorexia_best")
head(bp_from_anorexiac)
merge<- merge(merge, bp_from_anorexiac, by ="IID")
head(merge)


bp_from_anxa <- read.table("bp_from_anx/bp_from_anx.all_score", header=T, sep=" ")
head(bp_from_anxa)
bp_from_anxa <- subset(bp_from_anxa, select=-c(1))
bp_from_anxb <- read.table("bp_from_anx/bp_from_anx.best", header=T, sep=" ")
head(bp_from_anxb)
bp_from_anxb <- subset(bp_from_anxb, select=c(2,4))
bp_from_anxc<- merge(bp_from_anxa,bp_from_anxb, by ="IID")
colnames(bp_from_anxc)<- c("IID","bp_from_anx_e8","bp_from_anx_e5","bp_from_anx_e3", "bp_from_anx_e1", "bp_from_anx_1.0", "bp_from_anx_best")
head(bp_from_anxc)
merge<- merge(merge, bp_from_anxc, by ="IID")
head(merge)


bp_from_BDSCZvsCONTa <- read.table("bp_from_BDSCZvsCONT/bp_from_BDSCZvsCONT.all_score", header=T, sep=" ")
head(bp_from_BDSCZvsCONTa)
bp_from_BDSCZvsCONTa <- subset(bp_from_BDSCZvsCONTa, select=-c(1))
bp_from_BDSCZvsCONTb <- read.table("bp_from_BDSCZvsCONT/bp_from_BDSCZvsCONT.best", header=T, sep=" ")
head(bp_from_BDSCZvsCONTb)
bp_from_BDSCZvsCONTb <- subset(bp_from_BDSCZvsCONTb, select=c(2,4))
bp_from_BDSCZvsCONTc<- merge(bp_from_BDSCZvsCONTa,bp_from_BDSCZvsCONTb, by ="IID")
colnames(bp_from_BDSCZvsCONTc)<- c("IID","bp_from_BDSCZvsCONT_e8","bp_from_BDSCZvsCONT_e5","bp_from_BDSCZvsCONT_e3", "bp_from_BDSCZvsCONT_e1", "bp_from_BDSCZvsCONT_1.0", "bp_from_BDSCZvsCONT_best")
head(bp_from_BDSCZvsCONTc)
merge<- merge(merge, bp_from_BDSCZvsCONTc, by ="IID")
head(merge)


bp_from_BDvsCONTa <- read.table("bp_from_BDvsCONT/bp_from_BDvsCONT.all_score", header=T, sep=" ")
head(bp_from_BDvsCONTa)
bp_from_BDvsCONTa <- subset(bp_from_BDvsCONTa, select=-c(1))
bp_from_BDvsCONTb <- read.table("bp_from_BDvsCONT/bp_from_BDvsCONT.best", header=T, sep=" ")
head(bp_from_BDvsCONTb)
bp_from_BDvsCONTb <- subset(bp_from_BDvsCONTb, select=c(2,4))
bp_from_BDvsCONTc<- merge(bp_from_BDvsCONTa,bp_from_BDvsCONTb, by ="IID")
colnames(bp_from_BDvsCONTc)<- c("IID","bp_from_BDvsCONT_e8","bp_from_BDvsCONT_e5","bp_from_BDvsCONT_e3", "bp_from_BDvsCONT_e1", "bp_from_BDvsCONT_1.0", "bp_from_BDvsCONT_best")
head(bp_from_BDvsCONTc)
merge<- merge(merge, bp_from_BDvsCONTc, by ="IID")
head(merge)


bp_from_BMIa <- read.table("bp_from_BMI/bp_from_BMI.all_score", header=T, sep=" ")
head(bp_from_BMIa)
bp_from_BMIa <- subset(bp_from_BMIa, select=-c(1))
bp_from_BMIb <- read.table("bp_from_BMI/bp_from_BMI.best", header=T, sep=" ")
head(bp_from_BMIb)
bp_from_BMIb <- subset(bp_from_BMIb, select=c(2,4))
bp_from_BMIc<- merge(bp_from_BMIa,bp_from_BMIb, by ="IID")
colnames(bp_from_BMIc)<- c("IID","bp_from_BMI_e8","bp_from_BMI_e5","bp_from_BMI_e3", "bp_from_BMI_e1", "bp_from_BMI_1.0", "bp_from_BMI_best")
head(bp_from_BMIc)
merge<- merge(merge, bp_from_BMIc, by ="IID")
head(merge)


bp_from_CADa <- read.table("bp_from_CAD/bp_from_CAD.all_score", header=T, sep=" ")
head(bp_from_CADa)
bp_from_CADa <- subset(bp_from_CADa, select=-c(1))
bp_from_CADb <- read.table("bp_from_CAD/bp_from_CAD.best", header=T, sep=" ")
head(bp_from_CADb)
bp_from_CADb <- subset(bp_from_CADb, select=c(2,4))
bp_from_CADc<- merge(bp_from_CADa,bp_from_CADb, by ="IID")
colnames(bp_from_CADc)<- c("IID","bp_from_CAD_e8","bp_from_CAD_e5","bp_from_CAD_e3", "bp_from_CAD_e1", "bp_from_CAD_1.0", "bp_from_CAD_best")
head(bp_from_CADc)
merge<- merge(merge, bp_from_CADc, by ="IID")
head(merge)


bp_from_cannabisa <- read.table("bp_from_cannabis/bp_from_cannabis.all_score", header=T, sep=" ")
head(bp_from_cannabisa)
bp_from_cannabisa <- subset(bp_from_cannabisa, select=-c(1))
bp_from_cannabisb <- read.table("bp_from_cannabis/bp_from_cannabis.best", header=T, sep=" ")
head(bp_from_cannabisb)
bp_from_cannabisb <- subset(bp_from_cannabisb, select=c(2,4))
bp_from_cannabisc<- merge(bp_from_cannabisa,bp_from_cannabisb, by ="IID")
colnames(bp_from_cannabisc)<- c("IID","bp_from_cannabis_e8","bp_from_cannabis_e5","bp_from_cannabis_e3", "bp_from_cannabis_e1", "bp_from_cannabis_1.0", "bp_from_cannabis_best")
head(bp_from_cannabisc)
merge<- merge(merge, bp_from_cannabisc, by ="IID")
head(merge)


bp_from_sud2020-cuda <- read.table("bp_from_sud2020-cud/bp_from_sud2020-cud.all_score", header=T, sep=" ")
head(bp_from_sud2020-cuda)
bp_from_sud2020-cuda <- subset(bp_from_sud2020-cuda, select=-c(1))
bp_from_sud2020-cudb <- read.table("bp_from_sud2020-cud/bp_from_sud2020-cud.best", header=T, sep=" ")
head(bp_from_sud2020-cudb)
bp_from_sud2020-cudb <- subset(bp_from_sud2020-cudb, select=c(2,4))
bp_from_sud2020-cudc<- merge(bp_from_sud2020-cuda,bp_from_sud2020-cudb, by ="IID")
colnames(bp_from_sud2020-cudc)<- c("IID","bp_from_sud2020-cud_e8","bp_from_sud2020-cud_e5","bp_from_sud2020-cud_e3", "bp_from_sud2020-cud_e1", "bp_from_sud2020-cud_1.0", "bp_from_sud2020-cud_best")
head(bp_from_sud2020-cudc)
merge<- merge(merge, bp_from_sud2020-cudc, by ="IID")
head(merge)


bp_from_PGC_ADHDa <- read.table("bp_from_PGC_ADHD/bp_from_PGC_ADHD.all_score", header=T, sep=" ")
head(bp_from_PGC_ADHDa)
bp_from_PGC_ADHDa <- subset(bp_from_PGC_ADHDa, select=-c(1))
bp_from_PGC_ADHDb <- read.table("bp_from_PGC_ADHD/bp_from_PGC_ADHD.best", header=T, sep=" ")
head(bp_from_PGC_ADHDb)
bp_from_PGC_ADHDb <- subset(bp_from_PGC_ADHDb, select=c(2,4))
bp_from_PGC_ADHDc<- merge(bp_from_PGC_ADHDa,bp_from_PGC_ADHDb, by ="IID")
colnames(bp_from_PGC_ADHDc)<- c("IID","bp_from_PGC_ADHD_e8","bp_from_PGC_ADHD_e5","bp_from_PGC_ADHD_e3", "bp_from_PGC_ADHD_e1", "bp_from_PGC_ADHD_1.0", "bp_from_PGC_ADHD_best")
head(bp_from_PGC_ADHDc)
merge<- merge(merge, bp_from_PGC_ADHDc, by ="IID")
head(merge)


bp_from_collegea <- read.table("bp_from_college/bp_from_college.all_score", header=T, sep=" ")
head(bp_from_collegea)
bp_from_collegea <- subset(bp_from_collegea, select=-c(1))
bp_from_collegeb <- read.table("bp_from_college/bp_from_college.best", header=T, sep=" ")
head(bp_from_collegeb)
bp_from_collegeb <- subset(bp_from_collegeb, select=c(2,4))
bp_from_collegec<- merge(bp_from_collegea,bp_from_collegeb, by ="IID")
colnames(bp_from_collegec)<- c("IID","bp_from_college_e8","bp_from_college_e5","bp_from_college_e3", "bp_from_college_e1", "bp_from_college_1.0", "bp_from_college_best")
head(bp_from_collegec)
merge<- merge(merge, bp_from_collegec, by ="IID")
head(merge)


bp_from_memorya <- read.table("bp_from_memory/bp_from_memory.all_score", header=T, sep=" ")
head(bp_from_memorya)
bp_from_memorya <- subset(bp_from_memorya, select=-c(1))
bp_from_memoryb <- read.table("bp_from_memory/bp_from_memory.best", header=T, sep=" ")
head(bp_from_memoryb)
bp_from_memoryb <- subset(bp_from_memoryb, select=c(2,4))
bp_from_memoryc<- merge(bp_from_memorya,bp_from_memoryb, by ="IID")
colnames(bp_from_memoryc)<- c("IID","bp_from_memory_e8","bp_from_memory_e5","bp_from_memory_e3", "bp_from_memory_e1", "bp_from_memory_1.0", "bp_from_memory_best")
head(bp_from_memoryc)
merge<- merge(merge, bp_from_memoryc, by ="IID")
head(merge)


bp_from_ReactionTimea <- read.table("bp_from_ReactionTime/bp_from_ReactionTime.all_score", header=T, sep=" ")
head(bp_from_ReactionTimea)
bp_from_ReactionTimea <- subset(bp_from_ReactionTimea, select=-c(1))
bp_from_ReactionTimeb <- read.table("bp_from_ReactionTime/bp_from_ReactionTime.best", header=T, sep=" ")
head(bp_from_ReactionTimeb)
bp_from_ReactionTimeb <- subset(bp_from_ReactionTimeb, select=c(2,4))
bp_from_ReactionTimec<- merge(bp_from_ReactionTimea,bp_from_ReactionTimeb, by ="IID")
colnames(bp_from_ReactionTimec)<- c("IID","bp_from_ReactionTime_e8","bp_from_ReactionTime_e5","bp_from_ReactionTime_e3", "bp_from_ReactionTime_e1", "bp_from_ReactionTime_1.0", "bp_from_ReactionTime_best")
head(bp_from_ReactionTimec)
merge<- merge(merge, bp_from_ReactionTimec, by ="IID")
head(merge)


bp_from_VNRa <- read.table("bp_from_VNR/bp_from_VNR.all_score", header=T, sep=" ")
head(bp_from_VNRa)
bp_from_VNRa <- subset(bp_from_VNRa, select=-c(1))
bp_from_VNRb <- read.table("bp_from_VNR/bp_from_VNR.best", header=T, sep=" ")
head(bp_from_VNRb)
bp_from_VNRb <- subset(bp_from_VNRb, select=c(2,4))
bp_from_VNRc<- merge(bp_from_VNRa,bp_from_VNRb, by ="IID")
colnames(bp_from_VNRc)<- c("IID","bp_from_VNR_e8","bp_from_VNR_e5","bp_from_VNR_e3", "bp_from_VNR_e1", "bp_from_VNR_1.0", "bp_from_VNR_best")
head(bp_from_VNRc)
merge<- merge(merge, bp_from_VNRc, by ="IID")
head(merge)


bp_from_DSa <- read.table("bp_from_DS/bp_from_DS.all_score", header=T, sep=" ")
head(bp_from_DSa)
bp_from_DSa <- subset(bp_from_DSa, select=-c(1))
bp_from_DSb <- read.table("bp_from_DS/bp_from_DS.best", header=T, sep=" ")
head(bp_from_DSb)
bp_from_DSb <- subset(bp_from_DSb, select=c(2,4))
bp_from_DSc<- merge(bp_from_DSa,bp_from_DSb, by ="IID")
colnames(bp_from_DSc)<- c("IID","bp_from_DS_e8","bp_from_DS_e5","bp_from_DS_e3", "bp_from_DS_e1", "bp_from_DS_1.0", "bp_from_DS_best")
head(bp_from_DSc)
merge<- merge(merge, bp_from_DSc, by ="IID")
head(merge)


bp_from_YoSa <- read.table("bp_from_YoS/bp_from_YoS.all_score", header=T, sep=" ")
head(bp_from_YoSa)
bp_from_YoSa <- subset(bp_from_YoSa, select=-c(1))
bp_from_YoSb <- read.table("bp_from_YoS/bp_from_YoS.best", header=T, sep=" ")
head(bp_from_YoSb)
bp_from_YoSb <- subset(bp_from_YoSb, select=c(2,4))
bp_from_YoSc<- merge(bp_from_YoSa,bp_from_YoSb, by ="IID")
colnames(bp_from_YoSc)<- c("IID","bp_from_YoS_e8","bp_from_YoS_e5","bp_from_YoS_e3", "bp_from_YoS_e1", "bp_from_YoS_1.0", "bp_from_YoS_best")
head(bp_from_YoSc)
merge<- merge(merge, bp_from_YoSc, by ="IID")
head(merge)


bp_from_CDa <- read.table("bp_from_CD/bp_from_CD.all_score", header=T, sep=" ")
head(bp_from_CDa)
bp_from_CDa <- subset(bp_from_CDa, select=-c(1))
bp_from_CDb <- read.table("bp_from_CD/bp_from_CD.best", header=T, sep=" ")
head(bp_from_CDb)
bp_from_CDb <- subset(bp_from_CDb, select=c(2,4))
bp_from_CDc<- merge(bp_from_CDa,bp_from_CDb, by ="IID")
colnames(bp_from_CDc)<- c("IID","bp_from_CD_e8","bp_from_CD_e5","bp_from_CD_e3", "bp_from_CD_e1", "bp_from_CD_1.0", "bp_from_CD_best")
head(bp_from_CDc)
merge<- merge(merge, bp_from_CDc, by ="IID")
head(merge)


bp_from_IBDa <- read.table("bp_from_IBD/bp_from_IBD.all_score", header=T, sep=" ")
head(bp_from_IBDa)
bp_from_IBDa <- subset(bp_from_IBDa, select=-c(1))
bp_from_IBDb <- read.table("bp_from_IBD/bp_from_IBD.best", header=T, sep=" ")
head(bp_from_IBDb)
bp_from_IBDb <- subset(bp_from_IBDb, select=c(2,4))
bp_from_IBDc<- merge(bp_from_IBDa,bp_from_IBDb, by ="IID")
colnames(bp_from_IBDc)<- c("IID","bp_from_IBD_e8","bp_from_IBD_e5","bp_from_IBD_e3", "bp_from_IBD_e1", "bp_from_IBD_1.0", "bp_from_IBD_best")
head(bp_from_IBDc)
merge<- merge(merge, bp_from_IBDc, by ="IID")
head(merge)


bp_from_UCa <- read.table("bp_from_UC/bp_from_UC.all_score", header=T, sep=" ")
head(bp_from_UCa)
bp_from_UCa <- subset(bp_from_UCa, select=-c(1))
bp_from_UCb <- read.table("bp_from_UC/bp_from_UC.best", header=T, sep=" ")
head(bp_from_UCb)
bp_from_UCb <- subset(bp_from_UCb, select=c(2,4))
bp_from_UCc<- merge(bp_from_UCa,bp_from_UCb, by ="IID")
colnames(bp_from_UCc)<- c("IID","bp_from_UC_e8","bp_from_UC_e5","bp_from_UC_e3", "bp_from_UC_e1", "bp_from_UC_1.0", "bp_from_UC_best")
head(bp_from_UCc)
merge<- merge(merge, bp_from_UCc, by ="IID")
head(merge)


bp_from_opennessa <- read.table("bp_from_openness/bp_from_openness.all_score", header=T, sep=" ")
head(bp_from_opennessa)
bp_from_opennessa <- subset(bp_from_opennessa, select=-c(1))
bp_from_opennessb <- read.table("bp_from_openness/bp_from_openness.best", header=T, sep=" ")
head(bp_from_opennessb)
bp_from_opennessb <- subset(bp_from_opennessb, select=c(2,4))
bp_from_opennessc<- merge(bp_from_opennessa,bp_from_opennessb, by ="IID")
colnames(bp_from_opennessc)<- c("IID","bp_from_openness_e8","bp_from_openness_e5","bp_from_openness_e3", "bp_from_openness_e1", "bp_from_openness_1.0", "bp_from_openness_best")
head(bp_from_opennessc)
merge<- merge(merge, bp_from_opennessc, by ="IID")
head(merge)


bp_from_incomea <- read.table("bp_from_income/bp_from_income.all_score", header=T, sep=" ")
head(bp_from_incomea)
bp_from_incomea <- subset(bp_from_incomea, select=-c(1))
bp_from_incomeb <- read.table("bp_from_income/bp_from_income.best", header=T, sep=" ")
head(bp_from_incomeb)
bp_from_incomeb <- subset(bp_from_incomeb, select=c(2,4))
bp_from_incomec<- merge(bp_from_incomea,bp_from_incomeb, by ="IID")
colnames(bp_from_incomec)<- c("IID","bp_from_income_e8","bp_from_income_e5","bp_from_income_e3", "bp_from_income_e1", "bp_from_income_1.0", "bp_from_income_best")
head(bp_from_incomec)
merge<- merge(merge, bp_from_incomec, by ="IID")
head(merge)


bp_from_OPPHa <- read.table("bp_from_OPPH/bp_from_OPPH.all_score", header=T, sep=" ")
head(bp_from_OPPHa)
bp_from_OPPHa <- subset(bp_from_OPPHa, select=-c(1))
bp_from_OPPHb <- read.table("bp_from_OPPH/bp_from_OPPH.best", header=T, sep=" ")
head(bp_from_OPPHb)
bp_from_OPPHb <- subset(bp_from_OPPHb, select=c(2,4))
bp_from_OPPHc<- merge(bp_from_OPPHa,bp_from_OPPHb, by ="IID")
colnames(bp_from_OPPHc)<- c("IID","bp_from_OPPH_e8","bp_from_OPPH_e5","bp_from_OPPH_e3", "bp_from_OPPH_e1", "bp_from_OPPH_1.0", "bp_from_OPPH_best")
head(bp_from_OPPHc)
merge<- merge(merge, bp_from_OPPHc, by ="IID")
head(merge)


bp_from_Townsenda <- read.table("bp_from_Townsend/bp_from_Townsend.all_score", header=T, sep=" ")
head(bp_from_Townsenda)
bp_from_Townsenda <- subset(bp_from_Townsenda, select=-c(1))
bp_from_Townsendb <- read.table("bp_from_Townsend/bp_from_Townsend.best", header=T, sep=" ")
head(bp_from_Townsendb)
bp_from_Townsendb <- subset(bp_from_Townsendb, select=c(2,4))
bp_from_Townsendc<- merge(bp_from_Townsenda,bp_from_Townsendb, by ="IID")
colnames(bp_from_Townsendc)<- c("IID","bp_from_Townsend_e8","bp_from_Townsend_e5","bp_from_Townsend_e3", "bp_from_Townsend_e1", "bp_from_Townsend_1.0", "bp_from_Townsend_best")
head(bp_from_Townsendc)
merge<- merge(merge, bp_from_Townsendc, by ="IID")
head(merge)


bp_from_ASD2017a <- read.table("bp_from_ASD2017/bp_from_ASD2017.all_score", header=T, sep=" ")
head(bp_from_ASD2017a)
bp_from_ASD2017a <- subset(bp_from_ASD2017a, select=-c(1))
bp_from_ASD2017b <- read.table("bp_from_ASD2017/bp_from_ASD2017.best", header=T, sep=" ")
head(bp_from_ASD2017b)
bp_from_ASD2017b <- subset(bp_from_ASD2017b, select=c(2,4))
bp_from_ASD2017c<- merge(bp_from_ASD2017a,bp_from_ASD2017b, by ="IID")
colnames(bp_from_ASD2017c)<- c("IID","bp_from_ASD2017_e8","bp_from_ASD2017_e5","bp_from_ASD2017_e3", "bp_from_ASD2017_e1", "bp_from_ASD2017_1.0", "bp_from_ASD2017_best")
head(bp_from_ASD2017c)
merge<- merge(merge, bp_from_ASD2017c, by ="IID")
head(merge)


bp_from_TGa <- read.table("bp_from_TG/bp_from_TG.all_score", header=T, sep=" ")
head(bp_from_TGa)
bp_from_TGa <- subset(bp_from_TGa, select=-c(1))
bp_from_TGb <- read.table("bp_from_TG/bp_from_TG.best", header=T, sep=" ")
head(bp_from_TGb)
bp_from_TGb <- subset(bp_from_TGb, select=c(2,4))
bp_from_TGc<- merge(bp_from_TGa,bp_from_TGb, by ="IID")
colnames(bp_from_TGc)<- c("IID","bp_from_TG_e8","bp_from_TG_e5","bp_from_TG_e3", "bp_from_TG_e1", "bp_from_TG_1.0", "bp_from_TG_best")
head(bp_from_TGc)
merge<- merge(merge, bp_from_TGc, by ="IID")
head(merge)


bp_from_neuroticism2021a <- read.table("bp_from_neuroticism2021/bp_from_neuroticism2021.all_score", header=T, sep=" ")
head(bp_from_neuroticism2021a)
bp_from_neuroticism2021a <- subset(bp_from_neuroticism2021a, select=-c(1))
bp_from_neuroticism2021b <- read.table("bp_from_neuroticism2021/bp_from_neuroticism2021.best", header=T, sep=" ")
head(bp_from_neuroticism2021b)
bp_from_neuroticism2021b <- subset(bp_from_neuroticism2021b, select=c(2,4))
bp_from_neuroticism2021c<- merge(bp_from_neuroticism2021a,bp_from_neuroticism2021b, by ="IID")
colnames(bp_from_neuroticism2021c)<- c("IID","bp_from_neuroticism2021_e8","bp_from_neuroticism2021_e5","bp_from_neuroticism2021_e3", "bp_from_neuroticism2021_e1", "bp_from_neuroticism2021_1.0", "bp_from_neuroticism2021_best")
head(bp_from_neuroticism2021c)
merge<- merge(merge, bp_from_neuroticism2021c, by ="IID")
head(merge)


bp_from_ocd2017a <- read.table("bp_from_ocd2017/bp_from_ocd2017.all_score", header=T, sep=" ")
head(bp_from_ocd2017a)
bp_from_ocd2017a <- subset(bp_from_ocd2017a, select=-c(1))
bp_from_ocd2017b <- read.table("bp_from_ocd2017/bp_from_ocd2017.best", header=T, sep=" ")
head(bp_from_ocd2017b)
bp_from_ocd2017b <- subset(bp_from_ocd2017b, select=c(2,4))
bp_from_ocd2017c<- merge(bp_from_ocd2017a,bp_from_ocd2017b, by ="IID")
colnames(bp_from_ocd2017c)<- c("IID","bp_from_ocd2017_e8","bp_from_ocd2017_e5","bp_from_ocd2017_e3", "bp_from_ocd2017_e1", "bp_from_ocd2017_1.0", "bp_from_ocd2017_best")
head(bp_from_ocd2017c)
merge<- merge(merge, bp_from_ocd2017c, by ="IID")
head(merge)


bp_from_ASDa <- read.table("bp_from_ASD/bp_from_ASD.all_score", header=T, sep=" ")
head(bp_from_ASDa)
bp_from_ASDa <- subset(bp_from_ASDa, select=-c(1))
bp_from_ASDb <- read.table("bp_from_ASD/bp_from_ASD.best", header=T, sep=" ")
head(bp_from_ASDb)
bp_from_ASDb <- subset(bp_from_ASDb, select=c(2,4))
bp_from_ASDc<- merge(bp_from_ASDa,bp_from_ASDb, by ="IID")
colnames(bp_from_ASDc)<- c("IID","bp_from_ASD_e8","bp_from_ASD_e5","bp_from_ASD_e3", "bp_from_ASD_e1", "bp_from_ASD_1.0", "bp_from_ASD_best")
head(bp_from_ASDc)
merge<- merge(merge, bp_from_ASDc, by ="IID")
head(merge)


bp_from_alcdep2018a <- read.table("bp_from_alcdep2018/bp_from_alcdep2018.all_score", header=T, sep=" ")
head(bp_from_alcdep2018a)
bp_from_alcdep2018a <- subset(bp_from_alcdep2018a, select=-c(1))
bp_from_alcdep2018b <- read.table("bp_from_alcdep2018/bp_from_alcdep2018.best", header=T, sep=" ")
head(bp_from_alcdep2018b)
bp_from_alcdep2018b <- subset(bp_from_alcdep2018b, select=c(2,4))
bp_from_alcdep2018c<- merge(bp_from_alcdep2018a,bp_from_alcdep2018b, by ="IID")
colnames(bp_from_alcdep2018c)<- c("IID","bp_from_alcdep2018_e8","bp_from_alcdep2018_e5","bp_from_alcdep2018_e3", "bp_from_alcdep2018_e1", "bp_from_alcdep2018_1.0", "bp_from_alcdep2018_best")
head(bp_from_alcdep2018c)
merge<- merge(merge, bp_from_alcdep2018c, by ="IID")
head(merge)


bp_from_cdg2019a <- read.table("bp_from_cdg2019/bp_from_cdg2019.all_score", header=T, sep=" ")
head(bp_from_cdg2019a)
bp_from_cdg2019a <- subset(bp_from_cdg2019a, select=-c(1))
bp_from_cdg2019b <- read.table("bp_from_cdg2019/bp_from_cdg2019.best", header=T, sep=" ")
head(bp_from_cdg2019b)
bp_from_cdg2019b <- subset(bp_from_cdg2019b, select=c(2,4))
bp_from_cdg2019c<- merge(bp_from_cdg2019a,bp_from_cdg2019b, by ="IID")
colnames(bp_from_cdg2019c)<- c("IID","bp_from_cdg2019_e8","bp_from_cdg2019_e5","bp_from_cdg2019_e3", "bp_from_cdg2019_e1", "bp_from_cdg2019_1.0", "bp_from_cdg2019_best")
head(bp_from_cdg2019c)
merge<- merge(merge, bp_from_cdg2019c, by ="IID")
head(merge)


bp_from_depression2019a <- read.table("bp_from_depression2019/bp_from_depression2019.all_score", header=T, sep=" ")
head(bp_from_depression2019a)
bp_from_depression2019a <- subset(bp_from_depression2019a, select=-c(1))
bp_from_depression2019b <- read.table("bp_from_depression2019/bp_from_depression2019.best", header=T, sep=" ")
head(bp_from_depression2019b)
bp_from_depression2019b <- subset(bp_from_depression2019b, select=c(2,4))
bp_from_depression2019c<- merge(bp_from_depression2019a,bp_from_depression2019b, by ="IID")
colnames(bp_from_depression2019c)<- c("IID","bp_from_depression2019_e8","bp_from_depression2019_e5","bp_from_depression2019_e3", "bp_from_depression2019_e1", "bp_from_depression2019_1.0", "bp_from_depression2019_best")
head(bp_from_depression2019c)
merge<- merge(merge, bp_from_depression2019c, by ="IID")
head(merge)


bp_from_pgc3_scz2021a <- read.table("bp_from_pgc3_scz2021/bp_from_pgc3_scz2021.all_score", header=T, sep=" ")
head(bp_from_pgc3_scz2021a)
bp_from_pgc3_scz2021a <- subset(bp_from_pgc3_scz2021a, select=-c(1))
bp_from_pgc3_scz2021b <- read.table("bp_from_pgc3_scz2021/bp_from_pgc3_scz2021.best", header=T, sep=" ")
head(bp_from_pgc3_scz2021b)
bp_from_pgc3_scz2021b <- subset(bp_from_pgc3_scz2021b, select=c(2,4))
bp_from_pgc3_scz2021c<- merge(bp_from_pgc3_scz2021a,bp_from_pgc3_scz2021b, by ="IID")
colnames(bp_from_pgc3_scz2021c)<- c("IID","bp_from_pgc3_scz2021_e8","bp_from_pgc3_scz2021_e5","bp_from_pgc3_scz2021_e3", "bp_from_pgc3_scz2021_e1", "bp_from_pgc3_scz2021_1.0", "bp_from_pgc3_scz2021_best")
head(bp_from_pgc3_scz2021c)
merge<- merge(merge, bp_from_pgc3_scz2021c, by ="IID")
head(merge)


bp_from_AD2021a <- read.table("bp_from_AD2021/bp_from_AD2021.all_score", header=T, sep=" ")
head(bp_from_AD2021a)
bp_from_AD2021a <- subset(bp_from_AD2021a, select=-c(1))
bp_from_AD2021b <- read.table("bp_from_AD2021/bp_from_AD2021.best", header=T, sep=" ")
head(bp_from_AD2021b)
bp_from_AD2021b <- subset(bp_from_AD2021b, select=c(2,4))
bp_from_AD2021c<- merge(bp_from_AD2021a,bp_from_AD2021b, by ="IID")
colnames(bp_from_AD2021c)<- c("IID","bp_from_AD2021_e8","bp_from_AD2021_e5","bp_from_AD2021_e3", "bp_from_AD2021_e1", "bp_from_AD2021_1.0", "bp_from_AD2021_best")
head(bp_from_AD2021c)
merge<- merge(merge, bp_from_AD2021c, by ="IID")
head(merge)


bp_from_an2019a <- read.table("bp_from_an2019/bp_from_an2019.all_score", header=T, sep=" ")
head(bp_from_an2019a)
bp_from_an2019a <- subset(bp_from_an2019a, select=-c(1))
bp_from_an2019b <- read.table("bp_from_an2019/bp_from_an2019.best", header=T, sep=" ")
head(bp_from_an2019b)
bp_from_an2019b <- subset(bp_from_an2019b, select=c(2,4))
bp_from_an2019c<- merge(bp_from_an2019a,bp_from_an2019b, by ="IID")
colnames(bp_from_an2019c)<- c("IID","bp_from_an2019_e8","bp_from_an2019_e5","bp_from_an2019_e3", "bp_from_an2019_e1", "bp_from_an2019_1.0", "bp_from_an2019_best")
head(bp_from_an2019c)
merge<- merge(merge, bp_from_an2019c, by ="IID")
head(merge)


bp_from_bpall2021a <- read.table("bp_from_bpall2021/bp_from_bpall2021.all_score", header=T, sep=" ")
head(bp_from_bpall2021a)
bp_from_bpall2021a <- subset(bp_from_bpall2021a, select=-c(1))
bp_from_bpall2021b <- read.table("bp_from_bpall2021/bp_from_bpall2021.best", header=T, sep=" ")
head(bp_from_bpall2021b)
bp_from_bpall2021b <- subset(bp_from_bpall2021b, select=c(2,4))
bp_from_bpall2021c<- merge(bp_from_bpall2021a,bp_from_bpall2021b, by ="IID")
colnames(bp_from_bpall2021c)<- c("IID","bp_from_bpall2021_e8","bp_from_bpall2021_e5","bp_from_bpall2021_e3", "bp_from_bpall2021_e1", "bp_from_bpall2021_1.0", "bp_from_bpall2021_best")
head(bp_from_bpall2021c)
merge<- merge(merge, bp_from_bpall2021c, by ="IID")
head(merge)


bp_from_bpI2021a <- read.table("bp_from_bpI2021/bp_from_bpI2021.all_score", header=T, sep=" ")
head(bp_from_bpI2021a)
bp_from_bpI2021a <- subset(bp_from_bpI2021a, select=-c(1))
bp_from_bpI2021b <- read.table("bp_from_bpI2021/bp_from_bpI2021.best", header=T, sep=" ")
head(bp_from_bpI2021b)
bp_from_bpI2021b <- subset(bp_from_bpI2021b, select=c(2,4))
bp_from_bpI2021c<- merge(bp_from_bpI2021a,bp_from_bpI2021b, by ="IID")
colnames(bp_from_bpI2021c)<- c("IID","bp_from_bpI2021_e8","bp_from_bpI2021_e5","bp_from_bpI2021_e3", "bp_from_bpI2021_e1", "bp_from_bpI2021_1.0", "bp_from_bpI2021_best")
head(bp_from_bpI2021c)
merge<- merge(merge, bp_from_bpI2021c, by ="IID")
head(merge)


bp_from_bpII2021a <- read.table("bp_from_bpII2021/bp_from_bpII2021.all_score", header=T, sep=" ")
head(bp_from_bpII2021a)
bp_from_bpII2021a <- subset(bp_from_bpII2021a, select=-c(1))
bp_from_bpII2021b <- read.table("bp_from_bpII2021/bp_from_bpII2021.best", header=T, sep=" ")
head(bp_from_bpII2021b)
bp_from_bpII2021b <- subset(bp_from_bpII2021b, select=c(2,4))
bp_from_bpII2021c<- merge(bp_from_bpII2021a,bp_from_bpII2021b, by ="IID")
colnames(bp_from_bpII2021c)<- c("IID","bp_from_bpII2021_e8","bp_from_bpII2021_e5","bp_from_bpII2021_e3", "bp_from_bpII2021_e1", "bp_from_bpII2021_1.0", "bp_from_bpII2021_best")
head(bp_from_bpII2021c)
merge<- merge(merge, bp_from_bpII2021c, by ="IID")
head(merge)


bp_from_panic2019a <- read.table("bp_from_panic2019/bp_from_panic2019.all_score", header=T, sep=" ")
head(bp_from_panic2019a)
bp_from_panic2019a <- subset(bp_from_panic2019a, select=-c(1))
bp_from_panic2019b <- read.table("bp_from_panic2019/bp_from_panic2019.best", header=T, sep=" ")
head(bp_from_panic2019b)
bp_from_panic2019b <- subset(bp_from_panic2019b, select=c(2,4))
bp_from_panic2019c<- merge(bp_from_panic2019a,bp_from_panic2019b, by ="IID")
colnames(bp_from_panic2019c)<- c("IID","bp_from_panic2019_e8","bp_from_panic2019_e5","bp_from_panic2019_e3", "bp_from_panic2019_e1", "bp_from_panic2019_1.0", "bp_from_panic2019_best")
head(bp_from_panic2019c)
merge<- merge(merge, bp_from_panic2019c, by ="IID")
head(merge)


bp_from_ptsd_eura <- read.table("bp_from_ptsd_eur/bp_from_ptsd_eur.all_score", header=T, sep=" ")
head(bp_from_ptsd_eura)
bp_from_ptsd_eura <- subset(bp_from_ptsd_eura, select=-c(1))
bp_from_ptsd_eurb <- read.table("bp_from_ptsd_eur/bp_from_ptsd_eur.best", header=T, sep=" ")
head(bp_from_ptsd_eurb)
bp_from_ptsd_eurb <- subset(bp_from_ptsd_eurb, select=c(2,4))
bp_from_ptsd_eurc<- merge(bp_from_ptsd_eura,bp_from_ptsd_eurb, by ="IID")
colnames(bp_from_ptsd_eurc)<- c("IID","bp_from_ptsd_eur_e8","bp_from_ptsd_eur_e5","bp_from_ptsd_eur_e3", "bp_from_ptsd_eur_e1", "bp_from_ptsd_eur_1.0", "bp_from_ptsd_eur_best")
head(bp_from_ptsd_eurc)
merge<- merge(merge, bp_from_ptsd_eurc, by ="IID")
head(merge)


bp_from_SCZvsBDa <- read.table("bp_from_SCZvsBD/bp_from_SCZvsBD.all_score", header=T, sep=" ")
head(bp_from_SCZvsBDa)
bp_from_SCZvsBDa <- subset(bp_from_SCZvsBDa, select=-c(1))
bp_from_SCZvsBDb <- read.table("bp_from_SCZvsBD/bp_from_SCZvsBD.best", header=T, sep=" ")
head(bp_from_SCZvsBDb)
bp_from_SCZvsBDb <- subset(bp_from_SCZvsBDb, select=c(2,4))
bp_from_SCZvsBDc<- merge(bp_from_SCZvsBDa,bp_from_SCZvsBDb, by ="IID")
colnames(bp_from_SCZvsBDc)<- c("IID","bp_from_SCZvsBD_e8","bp_from_SCZvsBD_e5","bp_from_SCZvsBD_e3", "bp_from_SCZvsBD_e1", "bp_from_SCZvsBD_1.0", "bp_from_SCZvsBD_best")
head(bp_from_SCZvsBDc)
merge<- merge(merge, bp_from_SCZvsBDc, by ="IID")
head(merge)


bp_from_SCZvsCONTa <- read.table("bp_from_SCZvsCONT/bp_from_SCZvsCONT.all_score", header=T, sep=" ")
head(bp_from_SCZvsCONTa)
bp_from_SCZvsCONTa <- subset(bp_from_SCZvsCONTa, select=-c(1))
bp_from_SCZvsCONTb <- read.table("bp_from_SCZvsCONT/bp_from_SCZvsCONT.best", header=T, sep=" ")
head(bp_from_SCZvsCONTb)
bp_from_SCZvsCONTb <- subset(bp_from_SCZvsCONTb, select=c(2,4))
bp_from_SCZvsCONTc<- merge(bp_from_SCZvsCONTa,bp_from_SCZvsCONTb, by ="IID")
colnames(bp_from_SCZvsCONTc)<- c("IID","bp_from_SCZvsCONT_e8","bp_from_SCZvsCONT_e5","bp_from_SCZvsCONT_e3", "bp_from_SCZvsCONT_e1", "bp_from_SCZvsCONT_1.0", "bp_from_SCZvsCONT_best")
head(bp_from_SCZvsCONTc)
merge<- merge(merge, bp_from_SCZvsCONTc, by ="IID")
head(merge)


bp_from_SWBa <- read.table("bp_from_SWB/bp_from_SWB.all_score", header=T, sep=" ")
head(bp_from_SWBa)
bp_from_SWBa <- subset(bp_from_SWBa, select=-c(1))
bp_from_SWBb <- read.table("bp_from_SWB/bp_from_SWB.best", header=T, sep=" ")
head(bp_from_SWBb)
bp_from_SWBb <- subset(bp_from_SWBb, select=c(2,4))
bp_from_SWBc<- merge(bp_from_SWBa,bp_from_SWBb, by ="IID")
colnames(bp_from_SWBc)<- c("IID","bp_from_SWB_e8","bp_from_SWB_e5","bp_from_SWB_e3", "bp_from_SWB_e1", "bp_from_SWB_1.0", "bp_from_SWB_best")
head(bp_from_SWBc)
merge<- merge(merge, bp_from_SWBc, by ="IID")
head(merge)


bp_from_cpda <- read.table("bp_from_cpd/bp_from_cpd.all_score", header=T, sep=" ")
head(bp_from_cpda)
bp_from_cpda <- subset(bp_from_cpda, select=-c(1))
bp_from_cpdb <- read.table("bp_from_cpd/bp_from_cpd.best", header=T, sep=" ")
head(bp_from_cpdb)
bp_from_cpdb <- subset(bp_from_cpdb, select=c(2,4))
bp_from_cpdc<- merge(bp_from_cpda,bp_from_cpdb, by ="IID")
colnames(bp_from_cpdc)<- c("IID","bp_from_cpd_e8","bp_from_cpd_e5","bp_from_cpd_e3", "bp_from_cpd_e1", "bp_from_cpd_1.0", "bp_from_cpd_best")
head(bp_from_cpdc)
merge<- merge(merge, bp_from_cpdc, by ="IID")
head(merge)


bp_from_earlyVSlatera <- read.table("bp_from_earlyVSlater/bp_from_earlyVSlater.all_score", header=T, sep=" ")
head(bp_from_earlyVSlatera)
bp_from_earlyVSlatera <- subset(bp_from_earlyVSlatera, select=-c(1))
bp_from_earlyVSlaterb <- read.table("bp_from_earlyVSlater/bp_from_earlyVSlater.best", header=T, sep=" ")
head(bp_from_earlyVSlaterb)
bp_from_earlyVSlaterb <- subset(bp_from_earlyVSlaterb, select=c(2,4))
bp_from_earlyVSlaterc<- merge(bp_from_earlyVSlatera,bp_from_earlyVSlaterb, by ="IID")
colnames(bp_from_earlyVSlaterc)<- c("IID","bp_from_earlyVSlater_e8","bp_from_earlyVSlater_e5","bp_from_earlyVSlater_e3", "bp_from_earlyVSlater_e1", "bp_from_earlyVSlater_1.0", "bp_from_earlyVSlater_best")
head(bp_from_earlyVSlaterc)
merge<- merge(merge, bp_from_earlyVSlaterc, by ="IID")
head(merge)


bp_from_evrsmka <- read.table("bp_from_evrsmk/bp_from_evrsmk.all_score", header=T, sep=" ")
head(bp_from_evrsmka)
bp_from_evrsmka <- subset(bp_from_evrsmka, select=-c(1))
bp_from_evrsmkb <- read.table("bp_from_evrsmk/bp_from_evrsmk.best", header=T, sep=" ")
head(bp_from_evrsmkb)
bp_from_evrsmkb <- subset(bp_from_evrsmkb, select=c(2,4))
bp_from_evrsmkc<- merge(bp_from_evrsmka,bp_from_evrsmkb, by ="IID")
colnames(bp_from_evrsmkc)<- c("IID","bp_from_evrsmk_e8","bp_from_evrsmk_e5","bp_from_evrsmk_e3", "bp_from_evrsmk_e1", "bp_from_evrsmk_1.0", "bp_from_evrsmk_best")
head(bp_from_evrsmkc)
merge<- merge(merge, bp_from_evrsmkc, by ="IID")
head(merge)


bp_from_formera <- read.table("bp_from_former/bp_from_former.all_score", header=T, sep=" ")
head(bp_from_formera)
bp_from_formera <- subset(bp_from_formera, select=-c(1))
bp_from_formerb <- read.table("bp_from_former/bp_from_former.best", header=T, sep=" ")
head(bp_from_formerb)
bp_from_formerb <- subset(bp_from_formerb, select=c(2,4))
bp_from_formerc<- merge(bp_from_formera,bp_from_formerb, by ="IID")
colnames(bp_from_formerc)<- c("IID","bp_from_former_e8","bp_from_former_e5","bp_from_former_e3", "bp_from_former_e1", "bp_from_former_1.0", "bp_from_former_best")
head(bp_from_formerc)
merge<- merge(merge, bp_from_formerc, by ="IID")
head(merge)


bp_from_logonseta <- read.table("bp_from_logonset/bp_from_logonset.all_score", header=T, sep=" ")
head(bp_from_logonseta)
bp_from_logonseta <- subset(bp_from_logonseta, select=-c(1))
bp_from_logonsetb <- read.table("bp_from_logonset/bp_from_logonset.best", header=T, sep=" ")
head(bp_from_logonsetb)
bp_from_logonsetb <- subset(bp_from_logonsetb, select=c(2,4))
bp_from_logonsetc<- merge(bp_from_logonseta,bp_from_logonsetb, by ="IID")
colnames(bp_from_logonsetc)<- c("IID","bp_from_logonset_e8","bp_from_logonset_e5","bp_from_logonset_e3", "bp_from_logonset_e1", "bp_from_logonset_1.0", "bp_from_logonset_best")
head(bp_from_logonsetc)
merge<- merge(merge, bp_from_logonsetc, by ="IID")
head(merge)


bp_from_Tts2018a <- read.table("bp_from_Tts2018/bp_from_Tts2018.all_score", header=T, sep=" ")
head(bp_from_Tts2018a)
bp_from_Tts2018a <- subset(bp_from_Tts2018a, select=-c(1))
bp_from_Tts2018b <- read.table("bp_from_Tts2018/bp_from_Tts2018.best", header=T, sep=" ")
head(bp_from_Tts2018b)
bp_from_Tts2018b <- subset(bp_from_Tts2018b, select=c(2,4))
bp_from_Tts2018c<- merge(bp_from_Tts2018a,bp_from_Tts2018b, by ="IID")
colnames(bp_from_Tts2018c)<- c("IID","bp_from_Tts2018_e8","bp_from_Tts2018_e5","bp_from_Tts2018_e3", "bp_from_Tts2018_e1", "bp_from_Tts2018_1.0", "bp_from_Tts2018_best")
head(bp_from_Tts2018c)
merge<- merge(merge, bp_from_Tts2018c, by ="IID")
head(merge)


bp_from_anypsychotica <- read.table("bp_from_anypsychotic/bp_from_anypsychotic.all_score", header=T, sep=" ")
head(bp_from_anypsychotica)
bp_from_anypsychotica <- subset(bp_from_anypsychotica, select=-c(1))
bp_from_anypsychoticb <- read.table("bp_from_anypsychotic/bp_from_anypsychotic.best", header=T, sep=" ")
head(bp_from_anypsychoticb)
bp_from_anypsychoticb <- subset(bp_from_anypsychoticb, select=c(2,4))
bp_from_anypsychoticc<- merge(bp_from_anypsychotica,bp_from_anypsychoticb, by ="IID")
colnames(bp_from_anypsychoticc)<- c("IID","bp_from_anypsychotic_e8","bp_from_anypsychotic_e5","bp_from_anypsychotic_e3", "bp_from_anypsychotic_e1", "bp_from_anypsychotic_1.0", "bp_from_anypsychotic_best")
head(bp_from_anypsychoticc)
merge<- merge(merge, bp_from_anypsychoticc, by ="IID")
head(merge)


bp_from_distressing_psychotica <- read.table("bp_from_distressing_psychotic/bp_from_distressing_psychotic.all_score", header=T, sep=" ")
head(bp_from_distressing_psychotica)
bp_from_distressing_psychotica <- subset(bp_from_distressing_psychotica, select=-c(1))
bp_from_distressing_psychoticb <- read.table("bp_from_distressing_psychotic/bp_from_distressing_psychotic.best", header=T, sep=" ")
head(bp_from_distressing_psychoticb)
bp_from_distressing_psychoticb <- subset(bp_from_distressing_psychoticb, select=c(2,4))
bp_from_distressing_psychoticc<- merge(bp_from_distressing_psychotica,bp_from_distressing_psychoticb, by ="IID")
colnames(bp_from_distressing_psychoticc)<- c("IID","bp_from_distressing_psychotic_e8","bp_from_distressing_psychotic_e5","bp_from_distressing_psychotic_e3", "bp_from_distressing_psychotic_e1", "bp_from_distressing_psychotic_1.0", "bp_from_distressing_psychotic_best")
head(bp_from_distressing_psychoticc)
merge<- merge(merge, bp_from_distressing_psychoticc, by ="IID")
head(merge)


bp_from_multipepsychotica <- read.table("bp_from_multipepsychotic/bp_from_multipepsychotic.all_score", header=T, sep=" ")
head(bp_from_multipepsychotica)
bp_from_multipepsychotica <- subset(bp_from_multipepsychotica, select=-c(1))
bp_from_multipepsychoticb <- read.table("bp_from_multipepsychotic/bp_from_multipepsychotic.best", header=T, sep=" ")
head(bp_from_multipepsychoticb)
bp_from_multipepsychoticb <- subset(bp_from_multipepsychoticb, select=c(2,4))
bp_from_multipepsychoticc<- merge(bp_from_multipepsychotica,bp_from_multipepsychoticb, by ="IID")
colnames(bp_from_multipepsychoticc)<- c("IID","bp_from_multipepsychotic_e8","bp_from_multipepsychotic_e5","bp_from_multipepsychotic_e3", "bp_from_multipepsychotic_e1", "bp_from_multipepsychotic_1.0", "bp_from_multipepsychotic_best")
head(bp_from_multipepsychoticc)
merge<- merge(merge, bp_from_multipepsychoticc, by ="IID")
head(merge)


